# WRITE
## SYSTEM
CLEAR_STATUS = "*CLS"
RESET = "*RST"
SYSTEM_REMOTE = "SYST:REM"
FUNC_CURR = "FUNC CURR"
ALL_INPUTS_ON = "INP:ALL 1"
ALL_INPUTS_OFF = "INP:ALL 0"
## CHANNEL
INPUT_ON = "INP 1"
INPUT_OFF = "INP 0"
SHORT_ON = "INP:SHOR 1"
SHORT_OFF = "INP:SHOR 0"
SELECT_CHANNEL = "CHAN "
SET_CURR = "CURR "

# QUERY
## SYSTEM
INST_ID = "*IDN?"
## CHANNEL
FETCH_VOLT = "FETC:VOLT?"
FETCH_CURR = "FETC:CURR?"
